/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => EmptyFilesCleaner
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var EmptyFilesCleaner = class extends import_obsidian.Plugin {
  async onload() {
    this.addRibbonIcon("trash-2", "Find empty files", () => {
      new EmptyFilesModal(this.app).open();
    });
    this.addCommand({
      id: "find-empty-files",
      name: "Find and delete empty files",
      callback: () => {
        new EmptyFilesModal(this.app).open();
      }
    });
  }
};
var EmptyFilesModal = class extends import_obsidian.Modal {
  constructor(app) {
    super(app);
    this.emptyFiles = [];
    this.checkedFiles = /* @__PURE__ */ new Set();
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("empty-files-modal");
    const header = contentEl.createEl("div", { cls: "ef-header" });
    header.createEl("h2", { text: "\u{1F5D1}\uFE0F Empty Files Cleaner" });
    header.createEl("p", {
      text: "Scanning your vault for empty notes...",
      cls: "ef-subtitle"
    });
    const scanningEl = contentEl.createEl("div", {
      cls: "ef-scanning",
      text: "\u23F3 Scanning..."
    });
    await this.scanEmptyFiles();
    scanningEl.remove();
    if (this.emptyFiles.length === 0) {
      contentEl.createEl("div", {
        cls: "ef-empty-state",
        text: "\u2705 No empty files found! Your vault is clean."
      });
      new import_obsidian.ButtonComponent(contentEl).setButtonText("Close").setCta().onClick(() => this.close());
      return;
    }
    const statsBar = contentEl.createEl("div", { cls: "ef-stats" });
    const countEl = statsBar.createEl("span", {
      cls: "ef-count",
      text: `Found ${this.emptyFiles.length} empty file${this.emptyFiles.length !== 1 ? "s" : ""}`
    });
    const controls = contentEl.createEl("div", { cls: "ef-controls" });
    const selectAllBtn = controls.createEl("button", {
      cls: "ef-btn ef-btn-secondary",
      text: "Select all"
    });
    const deselectAllBtn = controls.createEl("button", {
      cls: "ef-btn ef-btn-secondary",
      text: "Deselect all"
    });
    selectAllBtn.addEventListener("click", () => {
      this.emptyFiles.forEach((f) => this.checkedFiles.add(f.path));
      this.updateCheckboxes();
      this.updateDeleteButton();
    });
    deselectAllBtn.addEventListener("click", () => {
      this.checkedFiles.clear();
      this.updateCheckboxes();
      this.updateDeleteButton();
    });
    this.listContainer = contentEl.createEl("div", { cls: "ef-list" });
    this.renderFileList();
    const footer = contentEl.createEl("div", { cls: "ef-footer" });
    const deleteBtn = footer.createEl("button", {
      cls: "ef-btn ef-btn-danger",
      attr: { id: "ef-delete-btn", disabled: "true" },
      text: "Delete selected (0)"
    });
    const cancelBtn = footer.createEl("button", {
      cls: "ef-btn ef-btn-ghost",
      text: "Cancel"
    });
    cancelBtn.addEventListener("click", () => this.close());
    deleteBtn.addEventListener("click", async () => {
      if (this.checkedFiles.size === 0)
        return;
      await this.deleteSelected(deleteBtn, countEl);
    });
  }
  async scanEmptyFiles() {
    const files = this.app.vault.getMarkdownFiles();
    this.emptyFiles = [];
    for (const file of files) {
      const content = await this.app.vault.read(file);
      if (content.trim() === "") {
        this.emptyFiles.push(file);
      }
    }
    this.emptyFiles.sort((a, b) => a.path.localeCompare(b.path));
  }
  renderFileList() {
    this.listContainer.empty();
    for (const file of this.emptyFiles) {
      const item = this.listContainer.createEl("div", { cls: "ef-item" });
      const checkbox = item.createEl("input", {
        type: "checkbox",
        cls: "ef-checkbox",
        attr: { "data-path": file.path }
      });
      checkbox.checked = this.checkedFiles.has(file.path);
      checkbox.addEventListener("change", () => {
        if (checkbox.checked) {
          this.checkedFiles.add(file.path);
        } else {
          this.checkedFiles.delete(file.path);
        }
        this.updateDeleteButton();
      });
      const info = item.createEl("div", { cls: "ef-item-info" });
      info.createEl("span", { cls: "ef-item-name", text: file.basename });
      info.createEl("span", { cls: "ef-item-path", text: file.path });
      item.addEventListener("click", (e) => {
        if (e.target.tagName !== "INPUT") {
          checkbox.checked = !checkbox.checked;
          checkbox.dispatchEvent(new Event("change"));
        }
      });
    }
  }
  updateCheckboxes() {
    const checkboxes = this.listContainer.querySelectorAll(".ef-checkbox");
    checkboxes.forEach((cb) => {
      cb.checked = this.checkedFiles.has(cb.dataset.path || "");
    });
  }
  updateDeleteButton() {
    const btn = document.getElementById("ef-delete-btn");
    if (!btn)
      return;
    const count = this.checkedFiles.size;
    btn.textContent = `Delete selected (${count})`;
    btn.disabled = count === 0;
    btn.toggleClass("ef-btn-danger--active", count > 0);
  }
  async deleteSelected(deleteBtn, countEl) {
    const confirmed = confirm(
      `Are you sure you want to permanently delete ${this.checkedFiles.size} file(s)? This cannot be undone.`
    );
    if (!confirmed)
      return;
    deleteBtn.disabled = true;
    deleteBtn.textContent = "Deleting...";
    let deleted = 0;
    const errors = [];
    for (const path of this.checkedFiles) {
      const file = this.app.vault.getAbstractFileByPath(path);
      if (file instanceof import_obsidian.TFile) {
        try {
          await this.app.vault.delete(file);
          deleted++;
        } catch (e) {
          errors.push(path);
        }
      }
    }
    if (errors.length > 0) {
      new import_obsidian.Notice(`\u26A0\uFE0F Could not delete ${errors.length} file(s).`);
    }
    new import_obsidian.Notice(`\u2705 Deleted ${deleted} empty file${deleted !== 1 ? "s" : ""}.`);
    this.checkedFiles.clear();
    await this.scanEmptyFiles();
    this.renderFileList();
    countEl.textContent = `Found ${this.emptyFiles.length} empty file${this.emptyFiles.length !== 1 ? "s" : ""}`;
    this.updateDeleteButton();
    if (this.emptyFiles.length === 0) {
      this.close();
      new import_obsidian.Notice("\u2705 All selected empty files have been deleted!");
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
